services:
  mongo:
    image: mongo:latest
    container_name: ${MONGO_HOST}
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}                # certains scripts ou apps peuvent l’utiliser
    volumes:
      - ${MONGO_VOLUME}:/data/db
  importer:
    build: ./importer
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongo
    environment:
      - DOCKMODE=True
volumes:
  mongo_prod_data: {}
  mongo_test_data: {}
