services:
  mongo:
    image: mongo:7
    env_file:
      - .env
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  importer:
    build: 
      context: .
      dockerfile: migration/Dockerfile    
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
    depends_on:
      - mongo
    environment:
      - DOCKMODE=True
volumes:
  mongo_data: